services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: ./api/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    restart: unless-stopped
    env_file: ./api/.env
    depends_on:
      - postgres

  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: worker
    restart: unless-stopped
    env_file: ./api/.env
    depends_on:
      - postgres
      - redis

  umami:
    image: docker.umami.is/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file: .env

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env.local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  pgdata:
  redis-data:
