services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env.api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    restart: unless-stopped
    env_file: .env.api      
    depends_on:
      - postgres

  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: worker
    restart: unless-stopped
    env_file: .env.api
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env.frontend

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/build/client:/usr/share/nginx/html:ro
    depends_on:
      - api
      - frontend

volumes:
  pgdata:
  redis-data:
